### ISSUE TITLE
Issue trying to un install PXE Server

### ISSUE THREAD

**Issue by CyberBlaed** [OpenMediaVault-Plugin-Developers/openmediavault-pxe#6]
Unusual issue, hopefully you can replicate the issue.

I am trying to remove the plugin from my system but I am unable too due to it being referenced in 'shared folders' by the PXE server.

when editing the PXE server settings, I am unable to set the drive to 'none' setting on shared folders option.
when it is selected, the box outline becomes red, and so i have to have it pointing to a drive, I cannot point it to NONE to remove it.

**Comment by ryecoaaron** [comment]
You don't have to set the shared folder to none to remove the plugin.

**Comment by CyberBlaed** [comment]
@ryecoaaron
That does not allow for a clean removal.
The settings still remain in the shared folder settings and as such you are unable to delete the drive’s entry within the OMVui.

I appreciate the suggestion, but i would like a clean removal of the app so the system doesn bug out on me, hence, bug report that its not accepting a “none” setting like all the other plugins.

**Comment by ryecoaaron** [comment]
@CyberBlaed If you remove the plugin, the shared folder reference stays in the database.  If you purge the plugin, the shared folder reference is deleted.  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-pxe/blob/master/debian/postrm

I didn't close the report because I am considering adding the option.  I was just letting you know that you don't have to have the option for a clean removal.

**Comment by CyberBlaed** [comment]
@ryecoaaron
Oh, i was unaware purging would remove the entry. Thankyou for the advice.
